Models/ViewModels/ManageUserRolesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace NewTiceAI.Models.ViewModels
{
    public class ManageUserRolesViewModel
    {
        public TAUser? BTUser { get; set; }

        public MultiSelectList? Roles { get; set; }

        public List<string>? SelectedRoles { get; set; }    
    }
}

Controllers/UserRolesController.cs
using NewTiceAI.Extensions;
using NewTiceAI.Models;
using NewTiceAI.Models.ViewModels;
using NewTiceAI.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;

namespace NewTiceAI.Controllers
{

    [Authorize(Roles = "Admin")]
    public class UserRolesController : TABaseController
    {
        private readonly IOrganizationService _organizationService;
        private readonly IBTRolesService _rolesService;

        public UserRolesController(IOrganizationService organizationService, IBTRolesService rolesService)
        {
            _organizationService = organizationService;
            _rolesService = rolesService;
        }

        [HttpGet]
        public async Task<IActionResult> ManageUserRoles()
        {
            // 1 - Add an instance of the ViewModel as a List (model)
            List<ManageUserRolesViewModel> model = new();
            // 2 -Get CompanyId
            int organizationId = User.Identity!.GetOrganizationId();
            // Get all company users
            List<TAUser> btUsers = await _organizationService.GetMembersAsync(organizationId);

            // 3 - Loop over the users to populate the ViewModel
            //      - instantiate single ViewModel
            //      - use _rolesService
            //      - Create multi-selects

            foreach (TAUser btUser in btUsers)
            {
                ManageUserRolesViewModel viewModel = new();
                viewModel.BTUser = btUser;
                IEnumerable<string> currentRoles = await _rolesService.GetUserRolesAsync(btUser);
                viewModel.Roles = new MultiSelectList(await _rolesService.GetBTRolesAsync(), "Name", "Name", currentRoles);

                model.Add(viewModel);
            }


            // 4 - Return the model to the View
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserRoles(ManageUserRolesViewModel member)
        {

            // Get the company Id
            //int organizationId = User.Identity!.GetOrganizationId();

            // Instantiate the BTUser
            TAUser? btUser = (await _organizationService.GetMembersAsync(_organizationId)).FirstOrDefault(u => u.Id == member.BTUser!.Id);

            // Get Roles for the User
            IEnumerable<string> currentRoles = await _rolesService.GetUserRolesAsync(btUser!);

            // Get Selected Roles for the User
            //string? selectedUserRoles = member.SelectedRoles!.FirstOrDefault();


            //Add User to new role
            if (member.SelectedRoles != null)
            {
                if (await _rolesService.RemoveUserFromRolesAsync(btUser!, currentRoles))
                {
                    //await _rolesService.AddUserToRoleAsync(btUser!, selectedUserRole);

                    foreach (string role in member.SelectedRoles)
                    {
                        await _rolesService.AddUserToRoleAsync(btUser!, role);
                    }
                }
            }
            else
            {
                // Navigate back to the View
                return RedirectToAction(nameof(ManageUserRoles));

            }

            return RedirectToAction("CompanyMembers", "Companies");   
        }

    }

}

Views/UserRoles/ManageUserRoles.cshtml
@model IEnumerable<NewTiceAI.Models.ViewModels.ManageUserRolesViewModel>

    <h2 class="m-t-0 h3"><b>Manage Member Roles </b></h2>
<div class="row row-cols-3">
    @foreach (var member in Model)
    {
        <div class="col col-md-4">
            <div class="card m-3">
                <div class="card-body">
                    <p class="text-muted font-13 m-b-30">
                        This form displays the current roles assigned to the user: <strong class="text-info">@member.BTUser!.FullName</strong>.
                        Use the dropdown to select the roles this user should be assigned.
                        Once roles are selected, click "Assign Roles" to submit the form.
                    </p>
                    <hr />
                    <form asp-action="ManageUserRoles" asp-controller="UserRoles" method=post>
                        <input type="hidden" asp-for="@member.BTUser.Id" />
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="@member.Roles" class="custom-label"> Roles for @member.BTUser.FullName </label>
                                    <select asp-for="@member.SelectedRoles" class="form-control" asp-items="@member.Roles" multiple>
                                    </select>
                                    <hr />
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Assign Role" class="btn btn-info" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    }
</div>